Repository logstash-plugins/logstash-integration-kafka, pull requests merged in 2021-07, with the labels that each got.

#94 Fix support for basic auth with the schema registry
  CHANGELOG.md
  kafka_test_setup.sh
  kafka_test_teardown.sh
  lib/logstash/inputs/kafka.rb
  lib/logstash/plugin_mixins/common.rb
  logstash-integration-kafka.gemspec
  spec/fixtures/jaas.config
  spec/fixtures/pwd
  spec/integration/inputs/kafka_spec.rb
  start_auth_schema_registry.sh
  start_schema_registry.sh
  stop_schema_registry.sh
Labels: status:approved

#97 Add option to skip validation when dealing with schema registry
  CHANGELOG.md
  docs/input-kafka.asciidoc
  lib/logstash/plugin_mixins/common.rb
  logstash-integration-kafka.gemspec
  spec/unit/inputs/kafka_spec.rb
Labels: status:changes-requested

#99 Doc: Remove outdated recommendation for settings
  CHANGELOG.md
  docs/input-kafka.asciidoc
  logstash-integration-kafka.gemspec
Labels: documentation, status:approved

#90 Improve wording on enable_auto_commit=false data safety
  docs/input-kafka.asciidoc
Labels: documentation, status:approved

#100 Doc: Update changelog with info/link to PR #90
  CHANGELOG.md
Labels: documentation, status:needs-review
